alias gccf="gcc -Wall -Wextra -Werror"
alias gccw="gcc -Wall -Wextra -Werror *.c && ./a.out"
alias gccA="gcc main.c libftprintf.a && ./a.out | cat -e"
alias normch="norminette -R CheckForbiddenSourceHeader"
alias normi="~/.local/bin/norminette"
